name: Checks
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: checks
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t caramonica/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true caramonica/docker-react npm test
